// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUSvsr5oXFq2bJU2fwNdJePqYuvD_8EvY',
    appId: '1:233819739459:web:51c4996d60e5837b224bf6',
    messagingSenderId: '233819739459',
    projectId: 'mindmate-9f6d3',
    authDomain: 'mindmate-9f6d3.firebaseapp.com',
    storageBucket: 'mindmate-9f6d3.firebasestorage.app',
    measurementId: 'G-7Y1YGMZQN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQY8Ia6-4T3gTo7lR5cU75FXrkhvvVyI0',
    appId: '1:233819739459:android:6596573b78057f21224bf6',
    messagingSenderId: '233819739459',
    projectId: 'mindmate-9f6d3',
    storageBucket: 'mindmate-9f6d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApgpqsdbtC6lshxaNIHV21M7BkGaL93Yw',
    appId: '1:233819739459:ios:7b61340c1d4b5815224bf6',
    messagingSenderId: '233819739459',
    projectId: 'mindmate-9f6d3',
    storageBucket: 'mindmate-9f6d3.firebasestorage.app',
    iosClientId: '233819739459-7a56tc1ojhmls16qi05p6snoqk74ucmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindmate',
  );
}